### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by alexforcetranquille** [marineam/efitools#1]
Hello everybody,

I just executed 'make' in the folder efitools and this gave me those errors : 

make
[...]
cc  -o cert-to-efi-sig-list cert-to-efi-sig-list.o -lcrypto lib/lib.a
cert-to-efi-sig-list.o : Dans la fonction « main » :
cert-to-efi-sig-list.c:(.text.startup+0xb8) : référence indéfinie vers « ERR_load_crypto_strings »
cert-to-efi-sig-list.c:(.text.startup+0xbd) : référence indéfinie vers « OpenSSL_add_all_digests »
cert-to-efi-sig-list.c:(.text.startup+0xc2) : référence indéfinie vers « OpenSSL_add_all_ciphers »
collect2: error: ld returned 1 exit status
Makefile:91 : la recette pour la cible « cert-to-efi-sig-list » a échouée
make: *** [cert-to-efi-sig-list] Erreur 1

find / -name libcrypto.a
/usr/lib/x86_64-linux-gnu/libcrypto.a
/usr/local/ssl/lib/libcrypto.a
/usr/local/lib/libcrypto.a

openssl version
OpenSSL 1.0.2l  25 May 2017

Thanks in advance.

**Comment by marineam** [comment]
Off the top of my head I don't know what the linking issue may be. Maybe there is a mismatch between the system version in `/usr/lib` and `/usr/local`?

However, this repo is a fork from a couple years ago, I'd suggest using the upstream version: https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git
